<a href="https://colab.research.google.com/github/sidh1603/1000_TrainablePara_CNN/blob/main/10000_TrainableParameters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers,models,datasets
import matplotlib.pyplot as plt
from tensorflow.keras.layers import BatchNormalization

In [19]:
from tensorflow.keras.datasets import mnist

In [20]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [21]:
X_train = X_train.astype('float32')/255
X_test = X_test.astype('float32')/255

print("X_train sample :",  X_train.shape )
print("X_test sample : " , X_test.shape)

X_train sample : (60000, 28, 28)
X_test sample :  (10000, 28, 28)


In [22]:
from keras.utils import np_utils

In [23]:
num_class = 10
y_train = np_utils.to_categorical(y_train,num_class)
y_test = np_utils.to_categorical(y_test,num_class)


print("one hot coding")
print("y_train : " , y_train[:10])


one hot coding
y_train :  [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, GlobalAveragePooling2D


img_rows , img_cols = 28,28

X_train = X_train.reshape(X_train.shape[0],img_rows,img_cols,1)
X_test = X_test.reshape(X_test.shape[0],img_rows,img_cols,1)

print("Input Shape :" , img_rows,img_cols,1)
print("X_Train Shape:" , X_train.shape[0])

Input Shape : 28 28 1
X_Train Shape: 60000


In [25]:

model = Sequential()
model.add(Conv2D(16,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
#model.add(BatchNormalization())
#model.add(Dropout(0.25))



model.add(Conv2D(16,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))



model.add(Flatten())
model.add(Dense(16,activation='relu'))
model.add(Dropout(0.25))

model.add(Dense(10,activation='sigmoid'))

model.summary()




Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_21 (Conv2D)          (None, 26, 26, 16)        160       
                                                                 
 max_pooling2d_11 (MaxPoolin  (None, 13, 13, 16)       0         
 g2D)                                                            
                                                                 
 conv2d_22 (Conv2D)          (None, 11, 11, 16)        2320      
                                                                 
 max_pooling2d_12 (MaxPoolin  (None, 5, 5, 16)         0         
 g2D)                                                            
                                                                 
 flatten_5 (Flatten)         (None, 400)               0         
                                                                 
 dense_10 (Dense)            (None, 16)               

In [26]:
model.compile(optimizer='rmsprop' , loss='categorical_crossentropy' , metrics=['accuracy'])

In [27]:
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.001,
    patience=20,
    verbose=2,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
)

In [28]:
EPOCHS = 100
history = model.fit(X_train,y_train , verbose = 2 , validation_data=(X_test,y_test),epochs  = EPOCHS,callbacks = early_stopping)

Epoch 1/100
1875/1875 - 7s - loss: 0.6114 - accuracy: 0.7934 - val_loss: 0.1346 - val_accuracy: 0.9611 - 7s/epoch - 4ms/step
Epoch 2/100
1875/1875 - 6s - loss: 0.3139 - accuracy: 0.8969 - val_loss: 0.0881 - val_accuracy: 0.9748 - 6s/epoch - 3ms/step
Epoch 3/100
1875/1875 - 7s - loss: 0.2463 - accuracy: 0.9178 - val_loss: 0.0729 - val_accuracy: 0.9785 - 7s/epoch - 4ms/step
Epoch 4/100
1875/1875 - 6s - loss: 0.2014 - accuracy: 0.9347 - val_loss: 0.0672 - val_accuracy: 0.9801 - 6s/epoch - 3ms/step
Epoch 5/100
1875/1875 - 6s - loss: 0.1761 - accuracy: 0.9430 - val_loss: 0.0634 - val_accuracy: 0.9836 - 6s/epoch - 3ms/step
Epoch 6/100
1875/1875 - 6s - loss: 0.1673 - accuracy: 0.9469 - val_loss: 0.0564 - val_accuracy: 0.9842 - 6s/epoch - 3ms/step
Epoch 7/100
1875/1875 - 6s - loss: 0.1609 - accuracy: 0.9494 - val_loss: 0.0567 - val_accuracy: 0.9836 - 6s/epoch - 3ms/step
Epoch 8/100
1875/1875 - 7s - loss: 0.1605 - accuracy: 0.9498 - val_loss: 0.0557 - val_accuracy: 0.9846 - 7s/epoch - 4ms/step


In [29]:
score = model.evaluate(X_test,y_test)
accuracy = 100*score[1]

print("Accuracy : " , accuracy)

313/313 [==============================] - 1s 3ms/step - loss: 0.0838 - accuracy: 0.9802
Accuracy :  98.01999926567078


In [52]:
model1 = Sequential()
model1.add(Conv2D(64,(3,3),activation='relu',input_shape=(28,28,1)))
model1.add(Conv2D(32,(1,1),activation='relu'))
model1.add(Conv2D(16,(1,1),activation='relu'))
model1.add(MaxPooling2D(pool_size=(2,2)))
#model.add(BatchNormalization())
#model.add(Dropout(0.25))



model1.add(Conv2D(16,(3,3),activation='relu'))
model1.add(Conv2D(10,(1,1),activation='relu'))
model1.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(BatchNormalization())


model1.add(Flatten())
model1.add(Dense(16,activation='relu'))
model1.add(Dropout(0.25))

model1.add(Dense(10,activation='sigmoid'))

model1.summary()

Model: "sequential_22"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_91 (Conv2D)          (None, 26, 26, 64)        640       
                                                                 
 conv2d_92 (Conv2D)          (None, 26, 26, 32)        2080      
                                                                 
 conv2d_93 (Conv2D)          (None, 26, 26, 16)        528       
                                                                 
 max_pooling2d_45 (MaxPoolin  (None, 13, 13, 16)       0         
 g2D)                                                            
                                                                 
 conv2d_94 (Conv2D)          (None, 11, 11, 16)        2320      
                                                                 
 conv2d_95 (Conv2D)          (None, 11, 11, 10)        170       
                                                     

In [53]:
model1.compile(optimizer='rmsprop' , loss='categorical_crossentropy' , metrics=['accuracy'])

In [54]:
model1_hist = model1.fit(X_train,y_train , verbose = 2 , validation_data=(X_test,y_test),epochs  = EPOCHS,callbacks = early_stopping)

Epoch 1/100
1875/1875 - 9s - loss: 0.5822 - accuracy: 0.8090 - val_loss: 0.1248 - val_accuracy: 0.9611 - 9s/epoch - 5ms/step
Epoch 2/100
1875/1875 - 9s - loss: 0.2850 - accuracy: 0.9066 - val_loss: 0.0821 - val_accuracy: 0.9750 - 9s/epoch - 5ms/step
Epoch 3/100
1875/1875 - 9s - loss: 0.2205 - accuracy: 0.9301 - val_loss: 0.0757 - val_accuracy: 0.9762 - 9s/epoch - 5ms/step
Epoch 4/100
1875/1875 - 9s - loss: 0.1917 - accuracy: 0.9383 - val_loss: 0.0657 - val_accuracy: 0.9804 - 9s/epoch - 5ms/step
Epoch 5/100
1875/1875 - 8s - loss: 0.1749 - accuracy: 0.9449 - val_loss: 0.0589 - val_accuracy: 0.9828 - 8s/epoch - 4ms/step
Epoch 6/100
1875/1875 - 8s - loss: 0.1687 - accuracy: 0.9470 - val_loss: 0.0647 - val_accuracy: 0.9823 - 8s/epoch - 4ms/step
Epoch 7/100
1875/1875 - 9s - loss: 0.1590 - accuracy: 0.9506 - val_loss: 0.0626 - val_accuracy: 0.9809 - 9s/epoch - 5ms/step
Epoch 8/100
1875/1875 - 9s - loss: 0.1558 - accuracy: 0.9516 - val_loss: 0.0538 - val_accuracy: 0.9825 - 9s/epoch - 5ms/step


In [34]:
model1_score = model1.evaluate(X_test,y_test)
accuracy = 100 * model1_score[1]

print("Accuracy : " , accuracy )

313/313 [==============================] - 1s 3ms/step - loss: 0.0766 - accuracy: 0.9800
Accuracy :  98.00000190734863
